<?php
   session_start();
   require_once('options.php');
   require_once('classes/Verify.php');
   require_once('classes/Security.php');
   require_once('classes/User.php');
   require_once('classes/Session.php');
   require_once('classes/Testimonial.php');
   require_once('classes/Project.php');
